print("Name :Teena Tom")
print("Reg No : SJC21MCA-2043")
import numpy as np
A=np.array([ [2, 4],[5, 6] ])
B=np.array([ [9, 3],[9, 6] ])
print("Matrix addition :")
C=A+B
print(C)
print("Matrix Substraction :")
C=A-B
print(C)
print("Multiply the individual elements of matrix :")
C=np.multiply(A,B)
print(C)
print("Divide the elements of the matrices :")
C=np.divide(A,B)
print(C)
print("Matrix Multiplication :")
C=np.matmul(A,B)
print(C)
print("Display transpose of the matrix :")
C=np.transpose(C)
print(C)
print("Sum of diagonal element of matrix :")
C=np.diagonal(C)
print("Diagonal elements are :")
print(C)
print("Sum of diagonal elements are :")
print(sum(C))